### ISSUE TITLE
Apply fitting only to a subset of the data

### ISSUE THREAD

**Issue by ciskakemper** [ICSM/ampere#31]
Following the description by Srinivasan et al. (2017), I want to fit the IRS spectrum only over the observed 8-35 micron range complemented with any photometry available at longer wavelengths (PACS or MIPS-70). This means that in pgQuasarSample.py I need to select a subset of the data in 'irs" and a subset of the data in 'phot' for the fitting. Perhaps this can be done as an additional argument to EmCeeSearch.

**Comment by pscicluna** [comment]
I've been looking into fixing this. Masked arrays present two issues:

1. They're about 5 times slower than regular arrays because they execute mainly in pure python rather than in C
2. They behave differently to regular arrays when performing linear algebra on them. 

As a result, it looks like the best approach is still a very hacky solution, but it should work. Basically, the original data will have to be copied to duplicate variables, and only the data not masked out will be in the variables used to do calculations. the unmask() method will then simply delete the masks and return the original data to prominence.

**Comment by pscicluna** [comment]
I think this is fixed, so closing for now. Please reopen if problems appear.
